<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>swig</string>
	</array>
	<key>foldingStartMarker</key>
	<string>{% (block|if|for|macro|autoescape)</string>
	<key>foldingStopMarker</key>
	<string>{% (endblock|endif|endfor|endmacro|endautoescape) %}</string>
	<key>name</key>
	<string>HTML (Swig)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Since html is valid in Swig templates include the html patterns</string>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{#</string>
			<key>end</key>
			<string>#}</string>
			<key>name</key>
			<string>comment.line.swig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$[a-z_\.]+</string>
			<key>end</key>
			<string></string>
			<key>name</key>
			<string>variable.other.swig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.swig.tagbraces</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>variable.other.swig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|(\s?)([^\( ]+)\b</string>
					<key>name</key>
					<string>support.function.filter.swig</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.other.swig.template.tag</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.other.swig.template.tag</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_]+</string>
					<key>name</key>
					<string>string.unquoted.swig.template.tag</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{%</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.swig.tagbraces</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%}</string>
			<key>name</key>
			<string>meta.scope.swig.template.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(extends|block|endblock|parent|include|import|for|empty|endfor|if|else|endif|autoescape|endautoescape|set|macro)\b</string>
					<key>name</key>
					<string>keyword.control.swig.template</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(and|or|not|in)\b</string>
					<key>name</key>
					<string>keyword.operator.twig.template</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.other.twig.template.tag</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.other.twig.template.tag</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{%</string>
					<key>end</key>
					<string>%}</string>
					<key>name</key>
					<string>string.other.twig.template.tag</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_]+</string>
					<key>name</key>
					<string>string.unquoted.twig.template.tag</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.swig</string>
	<key>uuid</key>
	<string>85880CFF-7FAE-4122-B8AE-55F6644DF6FE</string>
</dict>
</plist>
